name: Push docker images to Docker Hub on release.

on:
  push:
    branches:
      - release/*
jobs:
  tag_and_push:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: image_name
        name: Form proper Docker Image Name
        run: |
          OLD_DOCKER_IMAGE="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/client:stage-${{ github.sha }}"
          NEW_DOCKER_IMAGE="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/client:latest"

          echo "OLD_DOCKER_IMAGE=$OLD_DOCKER_IMAGE" >> $GITHUB_OUTPUT
          echo "NEW_DOCKER_IMAGE=$NEW_DOCKER_IMAGE" >> $GITHUB_OUTPUT

      - name: Logging into Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tagging and Pushing into Docker Registry
        run: |
          docker pull ${{ steps.image_name.outputs.OLD_DOCKER_IMAGE }}
          docker tag ${{ steps.image_name.outputs.OLD_DOCKER_IMAGE }} ${{ steps.image_name.outputs.NEW_DOCKER_IMAGE }}
          docker push ${{ steps.image_name.outputs.NEW_DOCKER_IMAGE }}
